# Enable NewCops globally
AllCops:
  NewCops: enable

# Exclude specified directories and files
AllCops:
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"

# Display cop names in RuboCop output
AllCops:
  DisplayCopNames: true

# Layout cop settings
Layout/LineLength:
  Max: 120

# Metrics cops settings
Metrics/MethodLength:
  Include:
    - "app/controllers/*"
    - "app/models/*"
  Max: 20
Metrics/AbcSize:
  Include:
    - "app/controllers/*"
    - "app/models/*"
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  AllowedMethods: ["describe"]
  Max: 30

# Style cops settings
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false

# Disable individual cops
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Layout/LineLength:
  Enabled: false
Lint/EmptyWhen:
  Enabled: false
Lint/DuplicateCaseCondition:
  Enabled: false
